all:
	nvcc -O3 simulator.cpp saif.cpp ../gpu-sim/gsimulator.cu ../vlib_gpu/vlib_gpu.cpp vcdoutput.cpp ../vlib/type1parser.cpp  ../vlib/type1component.cpp  ../vlib/libraryparser.cpp ../vlib/gatefunction.cpp  ../vlib/primitiveparser.cpp ../vcd_translator/vcdparser.cpp ../graph/netlist.cpp ../sdf/sdfparser.cpp ../vlib/portparser.cpp ../vlib2/vlib_files/lib.cpp ../vlib2/vlib_files/vlib.cpp 
