compile:
	g++ netlist.cpp ../vlib/libraryparser.cpp ../vlib/type1parser.cpp ../vlib/type1component.cpp ../vlib/primitiveparser.cpp ../vlib/gatefunction.cpp

run:
	./a.out ../../ICCAD2020_Benchmarks_03092020/ICCAD2020_Benchmarks/NV_nvdla_large_cc_sdprdma_sdp_rtest/NV_nvdla_GEN.gv ../vlib/example.vlib ../vlib/primitive.vlib
