all:
	g++ vlib_gpu.cpp ../vlib/type1parser.cpp  ../vlib/type1component.cpp  ../vlib/libraryparser.cpp ../vlib/gatefunction.cpp  ../vlib/primitiveparser.cpp ../vlib/portparser.cpp ../vlib2/vlib_files/lib.cpp ../vlib2/vlib_files/vlib.cpp
